In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [8]:
df=pd.read_csv('spam_ham_dataset.csv')

In [9]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [10]:
df.drop(["Unnamed: 0"],axis=1)

label                                               text  label_num
0      ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3     spam  Subject: photoshop , windows , office . cheap ...          1
4      ham  Subject: re : indian springs\r\nthis deal is t...          0
...    ...                                                ...        ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...          0
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...          0
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...          0
5169   ham  Subject: industrial worksheets for august 2000...          0
5170  spam  Subject: important online banking alert\r\ndea...          1

[5171 rows x 3 columns]

In [12]:
df.rename(columns={"label_num":"spam"},inplace=True)

In [14]:
df.head()

Unnamed: 0 label                                               text  spam
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...     0
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...     0
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3        4685  spam  Subject: photoshop , windows , office . cheap ...     1
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...     0

In [15]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [16]:
df.head()

label                                               text  spam
0   ham  Subject: enron methanol ; meter # : 988291\r\n...     0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...     0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3  spam  Subject: photoshop , windows , office . cheap ...     1
4   ham  Subject: re : indian springs\r\nthis deal is t...     0

In [18]:
df.groupby("label").describe()

spam                                   
        count mean  std  min  25%  50%  75%  max
label                                           
ham    3672.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam   1499.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.text,df.spam)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [40]:
X_train_count=cv.fit_transform(X_train)

In [41]:
X_train_count.toarray()

array([[ 0, 10,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [42]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [43]:
X_test_count=cv.transform(X_test)

In [44]:
model.score(X_test_count, y_test)

0.9822119102861562

In [46]:
model.predict(X_test_count)

array([0, 0, 0, ..., 1, 0, 0])

In [82]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB(alpha=0.5))])

In [83]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('nb', MultinomialNB(alpha=0.5))])

In [84]:
clf.predict(X_test)

array([0, 0, 0, ..., 1, 0, 0])

In [85]:
clf.score(X_test,y_test)

0.9860788863109049