In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [96]:
df=pd.read_csv("heart.csv")

In [97]:
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [98]:
df['HeartDisease'].value_counts()

1    508
0    410
Name: HeartDisease, dtype: int64

In [99]:
df.shape

(918, 12)

In [100]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [101]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [102]:
df=df[df['RestingBP']<=(df['RestingBP'].std()*3+df['RestingBP'].mean())]
df=df[df['Cholesterol']<=(df['Cholesterol'].std()*3+df['Cholesterol'].mean())]
df=df[df['Oldpeak']<=(df['Oldpeak'].std()*3+df['Oldpeak'].mean())]

In [103]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  902.000000  902.000000   902.000000  902.000000  902.000000   
mean    53.487805  131.854767   197.347007    0.232816  136.848115   
std      9.444115   17.682612   107.585613    0.422860   25.451226   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.000000    0.000000  120.000000   
50%     54.000000  130.000000   222.000000    0.000000  138.000000   
75%     60.000000  140.000000   266.000000    0.000000  156.000000   
max     77.000000  185.000000   518.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  902.000000    902.000000  
mean     0.857428      0.548780  
std      1.013157      0.497891  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.500000      1.000000  
75%      1.500000      1.000000  
max      4.000000      1.000000

In [104]:
from sklearn.preprocessing import LabelEncoder

label=LabelEncoder()
df["RestingECG"]=label.fit_transform(df["RestingECG"])
df["ExerciseAngina"]=label.fit_transform(df["ExerciseAngina"])
df["ST_Slope"]=label.fit_transform(df["ST_Slope"])

In [105]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M           ATA        140          289          0           1   
1   49   F           NAP        160          180          0           1   
2   37   M           ATA        130          283          0           2   
3   48   F           ASY        138          214          0           1   
4   54   M           NAP        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [106]:
df['Sex']=pd.get_dummies(df['Sex'],drop_first=True)

In [107]:
df.head()

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1           ATA        140          289          0           1   
1   49    0           NAP        160          180          0           1   
2   37    1           ATA        130          283          0           2   
3   48    0           ASY        138          214          0           1   
4   54    1           NAP        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [108]:
df=pd.get_dummies(df,drop_first=True)

In [86]:
df.head()

Age  Sex  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0   40    1        140          289          0           1    172   
1   49    0        160          180          0           1    156   
2   37    1        130          283          0           2     98   
3   48    0        138          214          0           1    108   
4   54    1        150          195          0           1    122   

   ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  ChestPainType_ATA  \
0               0      0.0         2             0                  1   
1               0      1.0         1             1                  0   
2               0      0.0         2             0                  1   
3               1      1.5         1             1                  0   
4               0      0.0         2             0                  0   

   ChestPainType_NAP  ChestPainType_TA  
0                  0                 0  
1                  1                 0  
2                  0                 0  
3                  0                 0  
4                  1                 0

In [111]:
X=df.drop("HeartDisease",axis=1)
y=df.HeartDisease

In [112]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()

X_scaled=scale.fit_transform(X)

In [113]:
X_scaled

array([[-1.42896269,  0.51485643,  0.46089071, ...,  2.06757196,
        -0.53547478, -0.22914788],
       [-0.47545956, -1.94228905,  1.5925728 , ..., -0.4836591 ,
         1.86750159, -0.22914788],
       [-1.74679706,  0.51485643, -0.10495034, ...,  2.06757196,
        -0.53547478, -0.22914788],
       ...,
       [ 0.37209878,  0.51485643, -0.10495034, ..., -0.4836591 ,
        -0.53547478, -0.22914788],
       [ 0.37209878, -1.94228905, -0.10495034, ...,  2.06757196,
        -0.53547478, -0.22914788],
       [-1.64085227,  0.51485643,  0.3477225 , ..., -0.4836591 ,
         1.86750159, -0.22914788]])

In [114]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [115]:
y.value_counts()

1    495
0    407
Name: HeartDisease, dtype: int64

In [117]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=40)

In [118]:
X_train

array([[ 0.1602092 ,  0.51485643,  0.23455429, ..., -0.4836591 ,
         1.86750159, -0.22914788],
       [-1.74679706, -1.94228905, -0.67079139, ..., -0.4836591 ,
         1.86750159, -0.22914788],
       [-0.89923873, -1.94228905,  0.3477225 , ..., -0.4836591 ,
        -0.53547478, -0.22914788],
       ...,
       [ 0.05426441,  0.51485643, -1.23663243, ...,  2.06757196,
        -0.53547478, -0.22914788],
       [-2.17057623,  0.51485643, -0.67079139, ..., -0.4836591 ,
         1.86750159, -0.22914788],
       [ 0.26615399,  0.51485643, -0.95371191, ..., -0.4836591 ,
        -0.53547478, -0.22914788]])

In [119]:
X_train.shape

(631, 13)

In [120]:
X_test.shape

(271, 13)

In [121]:
rf=RandomForestClassifier()

In [122]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [124]:
rf.predict(X_test)

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0])

In [125]:
rf.score(X_test,y_test)

0.8634686346863468

In [126]:
from sklearn.model_selection import cross_val_score

In [129]:
x=cross_val_score(rf,X_scaled,y,cv=5)
x.mean()

0.8236893799877226

In [132]:
parameters={
    "n_estimators":[50,100,200,300,500],
    "criterion":['gini','entropy'],
    "max_depth" : [2,4,8,None],
    "max_features":['auto','sqrt','log2'],
    "bootstrap":[True,False]

}

In [133]:
rf=RandomForestClassifier()

In [136]:
from sklearn.model_selection import GridSearchCV
score=GridSearchCV(estimator=rf,param_grid=parameters,cv=5,n_jobs=-1)

In [137]:
score.fit(X_scaled,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 4, 8, None],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [50, 100, 200, 300, 500]})

In [138]:
score.best_params_

{'bootstrap': False,
 'criterion': 'gini',
 'max_depth': 4,
 'max_features': 'sqrt',
 'n_estimators': 50}

In [139]:
score.best_score_

0.8369736034376919