In [1]:
import numpy as np

In [5]:
arr=np.zeros(10)

In [8]:
arr.size

10

In [9]:
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
arr=np.arange(10,49)

In [11]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
arr=arr[::-1]

In [13]:
arr

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [14]:
arr1=np.arange(9).reshape(3,3)

In [15]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr=np.array([1,2,0,0,4,0])

In [17]:
arr

array([1, 2, 0, 0, 4, 0])

In [23]:
nz=np.nonzero([1,2,0,0,4,0])

In [24]:
nz

(array([0, 1, 4]),)

In [26]:
arr=np.identity(3).reshape(3,3)

In [27]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr=np.random.random((3,3,3))

In [29]:
arr

array([[[0.82200771, 0.34972885, 0.49257259],
        [0.86698727, 0.1685331 , 0.09364978],
        [0.88409009, 0.06395222, 0.28288067]],

       [[0.21967538, 0.05193618, 0.75791585],
        [0.32162262, 0.78787311, 0.72166345],
        [0.3235466 , 0.96137159, 0.02707365]],

       [[0.28903991, 0.09856058, 0.56535725],
        [0.44912025, 0.77011134, 0.29637421],
        [0.73384162, 0.62353829, 0.89831476]]])

In [30]:
arr=np.arange(100).reshape(10,10)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
arr.max()

99

In [33]:
arr.min()

0

In [38]:
arr=np.random.random((10,10))

In [39]:
arr

array([[0.23526851, 0.92458316, 0.33075386, 0.75707491, 0.52920995,
        0.00254806, 0.26527214, 0.07867934, 0.72654734, 0.09499672],
       [0.11111765, 0.60763469, 0.80496689, 0.69561825, 0.801942  ,
        0.04797532, 0.79859807, 0.67868383, 0.78265532, 0.61187979],
       [0.82131593, 0.6751007 , 0.45285435, 0.48495414, 0.32256981,
        0.96605019, 0.49948641, 0.34464833, 0.24315083, 0.29355062],
       [0.83897111, 0.50617567, 0.11290774, 0.96643397, 0.28490786,
        0.31296814, 0.28034452, 0.07917379, 0.56622129, 0.03945407],
       [0.53349033, 0.69103193, 0.46080532, 0.43601219, 0.25595204,
        0.81399472, 0.69986664, 0.22688566, 0.28068841, 0.78480398],
       [0.76358503, 0.87094629, 0.45141006, 0.68681239, 0.74415798,
        0.1297004 , 0.74804331, 0.10767714, 0.88806812, 0.06364999],
       [0.57860815, 0.07356748, 0.86159966, 0.30871573, 0.94003745,
        0.42471656, 0.40069112, 0.47921156, 0.80783325, 0.95772743],
       [0.49966624, 0.00180279, 0.5164528